### PR TITLE
Support more optional parameters

### PR DESCRIPTION
**Pull request by miyucy**
https://www.twilio.com/docs/sms/api/message-resource#create-a-message-resource
https://github.com/twilio/twilio-ruby/blob/main/lib/twilio-ruby/rest/api/v2010/account/message.rb#L30-L110

### CODE REVIEW

**Comment by alexford** [comment]
Thanks for doing this — however I think I'd rather we do this in a generalized way rather than continue to add more (See #19) so that we don't have to test each parameter and keep up to date with Twilio's API.

I went ahead and merged your StatusCallback one, but I think we're at the limit.

**Comment by miyucy** [comment]
Thanks for comment!

>  I think I'd rather we do this in a generalized way

So, What do you think to convert a hash key to UpperCamelCase?

Like this:

```ruby
# @param [Hash] args
def twilio_params(args)
  args.transform_keys { |key| key.to_s.gsub(/(?:\A|_)([a-z])/i) { |m| m[-1].upcase } }.compact
end
# pp twilio_params(to: "foo", media_url: 'bar')
# => {"To"=>"foo", "MediaUrl"=>"bar"}
```

**Comment by alexford** [comment]
> So, What do you think to convert a hash key to UpperCamelCase?

Yes, something like that exactly. As long as we can still check the _required_ arguments correctly and use that kind of transformation to catch all the optional ones

**Comment by alexford** [comment]
Replaced by #23

**Pull request closed without merging**
